from pexpect import TIMEOUT


LOTATION_MESSAGE = 'LOTAÇÃO ESGOTADA!!'
PORT = 12000
ADD_PLAYER = '(ADD_PLAYER)'
REMOVE_PLAYER = '(REMOVE_PLAYER)'
JOINNED_PLAYER = '(JOINNED_PLAYER)'
CHAT = '(CHAT)'
END_ROUND = '(END_ROUND)'
SINGLE_PLAYER_MESSAGE = 'SINGLE_PLAYER_MESSAGE'
ALL_PLAYER_MESSAGE = 'ALL_PLAYER_MESSAGE'
QUIT = 'QUIT'
DISCONNECTED_SERVER = 'Servidor desconectado'
TIMEOUT = 'TIMEOUT'
START_GAME = 'START GAME'
