listOfQuiz = [('"College" é a tradução de "faculdade" para qual idioma?', 'ingles'),
('"Universidad" é a tradução de "faculdade" para qual idioma?', 'espanhol'),
('"Université" é a tradução de "faculdade" para qual idioma?', 'frances'),
('"Hochschule" é a tradução de "faculdade" para qual idioma?', 'alemao'),
('"Università" é a tradução de "faculdade" para qual idioma?', 'italiano'),
('"大学" é a tradução de "faculdade" para qual idioma?', 'mandarim'),
('"collegium" é a tradução de "faculdade" para qual idioma?', 'latim'),
('"カレッジ" é a tradução de "faculdade" para qual idioma?', 'japones'),
('"kolej" é a tradução de "faculdade" para qual idioma?', 'turco'),
('"коледж" é a tradução de "faculdade" para qual idioma?', 'ucraniano'),
('"kollegium" é a tradução de "faculdade" para qual idioma?', 'dinamarques'),
('"kolidž" é a tradução de "faculdade" para qual idioma?', 'esloveno'),
('"kulanui" é a tradução de "faculdade" para qual idioma?', 'havaiano'),
('"kolegj" é a tradução de "faculdade" para qual idioma?', 'albanes'),
('"колледж" é a tradução de "faculdade" para qual idioma?', 'russo'),
('"kolehiyo" é a tradução de "faculdade" para qual idioma?', 'filipino'),
('"Κολλέγιο" é a tradução de "faculdade" para qual idioma?', 'grego'),
('"middelbare school" é a tradução de "faculdade" para qual idioma?', 'holandes'),
('"대학" é a tradução de "faculdade" para qual idioma?', 'coreano'),
('"vysoká škola" é a tradução de "faculdade" para qual idioma?', 'tcheco')]
